service: training-service

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

  environment:
    TRAINING_TYPES_TABLE: TrainingTypes-${sls:stage}
    TRAININGS_TABLE: Trainings-${sls:stage}

  httpApi:
    cors: true

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchGetItem
          Resource:
            - "arn:aws:dynamodb:${aws:region}:*:table/*"

  stage: ${opt:stage, 'dev'}
  region: eu-north-1

package:
  include:
    - helpers/**

functions:
  getTrainingTypes:
    handler: training/getTypes.handler
    events:
      - httpApi:
          path: /trainings/types
          method: get

  addTraining:
    handler: training/addTraining.handler
    events:
      - httpApi:
          path: /trainings
          method: post

  getAllTrainings:
    handler: training/getAllTrainings.handler
    events:
      - httpApi:
          path: /trainings
          method: get

  searchTrainings:
    handler: training/searchTrainings.handler
    events:
      - httpApi:
          path: /trainings/search
          method: get

resources:
  Resources:
    TrainingTypesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TRAINING_TYPES_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    TrainingsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TRAININGS_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: studentId
            AttributeType: S
          - AttributeName: trainerId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: StudentIdIndex
            KeySchema:
              - AttributeName: studentId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: TrainerIdIndex
            KeySchema:
              - AttributeName: trainerId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
